String appName = 'Paróquia São Sebastião';
String appVersion = 'v1.02';
int releaseVersion = 2;
String releaseDate = '2026.02.14';
bool showDebugBanner = false;
bool enableDebugPrint = true;
bool enableCronograma = true;
bool enableGame = false;
bool enableIA = true;
String aiWhatsapp = "https://api.whatsapp.com/send/?phone=18888186248";
bool enableDiocese = false;
bool enableSocial = true;
bool enableCreditos = true;
